# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{interfacelift}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Michel de Graaf", "Jeroen van Schagen"]
  s.date = %q{2009-11-20}
  s.default_executable = %q{interfacelift}
  s.description = %q{Installs themes and other layout/interface related resources}
  s.email = ["michel@re-invention.nl", "jeroen.v.schagen@gmail.com"]
  s.executables = ["interfacelift"]
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".DS_Store",
     ".gitignore",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/interfacelift",
     "docs/todo.txt",
     "interfacelift.gemspec",
     "lib/.DS_Store",
     "lib/catalog.rb",
     "lib/fetcher.rb",
     "lib/installer.rb",
     "lib/interfacelift.rb",
     "rdoc/classes/InterfaceLift.html",
     "rdoc/classes/InterfaceLift/Catalog.html",
     "rdoc/classes/InterfaceLift/Fetcher.html",
     "rdoc/classes/InterfaceLift/Installer.html",
     "rdoc/classes/InterfaceLift/ThemeManager.html",
     "rdoc/created.rid",
     "rdoc/files/lib/catalog_rb.html",
     "rdoc/files/lib/fetcher_rb.html",
     "rdoc/files/lib/installer_rb.html",
     "rdoc/files/lib/interfacelift_rb.html",
     "rdoc/files/lib/templates/bright_admin/install_rb.html",
     "rdoc/files/lib/theme_manager_rb.html",
     "rdoc/fr_class_index.html",
     "rdoc/fr_file_index.html",
     "rdoc/fr_method_index.html",
     "rdoc/index.html",
     "rdoc/rdoc-style.css",
     "spec/assets/README",
     "spec/assets/test_theme/README",
     "spec/assets/test_theme2/README",
     "spec/catalog_spec.rb",
     "spec/fetcher_spec.rb",
     "spec/installer_spec.rb",
     "spec/interfacelift_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/michel/interfacelift}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Installs templates in rails applications}
  s.test_files = [
    "spec/catalog_spec.rb",
     "spec/fetcher_spec.rb",
     "spec/installer_spec.rb",
     "spec/interfacelift_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<commander>, [">= 0"])
      s.add_runtime_dependency(%q<git>, [">= 0"])
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<commander>, [">= 0"])
      s.add_dependency(%q<git>, [">= 0"])
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<commander>, [">= 0"])
    s.add_dependency(%q<git>, [">= 0"])
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end

